### ISSUE TITLE
Create Dockerfile template for binary manifest

### ISSUE THREAD

**Issue by KSAlpha** [PLUS-POSTECH/soma#12]
Create a `Dockerfile` template which will be used for image generation.

It should be able to reflect all the options and features specified in the following example manifest:

```toml
name = "disposable"

[[executable]]
path = "deploy/home/disposable"
public = true

[[readonly]]
path = "deploy/home/flag"

[binary]
os = "ubuntu:16.04"
entry = "./disposable"
```
