### ISSUE TITLE
Implement soma repository manifest deserialization

### ISSUE THREAD

**Issue by KSAlpha** [PLUS-POSTECH/soma#8]
All soma repositories must setup `soma.toml` on their root directory.

It will initially support binary executable only.

For example, if you want to setup the soma repository which
  * name of the problem is `disposable`
  * position of the executable is `/home/disposable`
  * executable is available to download for challengers
  * position of the flag is `/home/flag`
  * flag is a read-only file
  * service runs on ubuntu:16.04 and not self-hosted

then the content of `soma.toml` should be written as following:

```toml
name = "disposable"

[[executable]]
path = "deploy/home/disposable"
public = true

[[readonly]]
path = "deploy/home/flag"

[binary]
os = "ubuntu:16.04"
entry = "./disposable"
```
